server:
  port: 5200
spring:
  application:
    name: gateway
  cloud:
    gateway:
      # 配置路由
      routes:
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

