spring:
  application:
    name: users
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.114.79.111:5432/yyh_test?currentSchema=vector_test
    username: HuntForWind
    password: ${DB_PASSWORD:19900318Yyh$}
server:
  port: 8083

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/  # 设置Eureka服务器的地址，用于服务发现与注册
  instance:
    instance-id: users2

springdoc:
  api-docs:
    path: /users2/api-docs
    enabled: true
  swagger-ui:
    url: /users2/api-docs
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    enabled: true
