spring:
  application:
    name: users
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/  # 设置Eureka服务器的地址，用于服务发现与注册
  instance:
    instance-id: users3